---
name: Apache Chef Test

on:
  pull_request:

jobs:
  markdownlint:
    uses: chef/github-workflows/.github/workflows/markdown-lint.yml@main

  yamllint:
    uses: chef/github-workflows/.github/workflows/yaml-lint.yml@main

  jsonlint:
    uses: chef/github-workflows/.github/workflows/json-lint.yml@main

  cookstylelint:
    uses: chef/github-workflows/.github/workflows/cookstyle-lint.yml@main
  
  integration-ubuntu-20_04:
    runs-on: ubuntu-20.04
    needs:
      - markdownlint
      - yamllint
      - jsonlint
      - cookstylelint
    strategy:
      matrix:
        os:
          - ubuntu-2004
        suite:
          - default
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Test-Kitchen Converge
        uses: actionshub/test-kitchen@main
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          action: converge
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.yml
      - name: Test-Kitchen Verify
        uses: actionshub/test-kitchen@main
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
          action: verify
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.yml

  check:
    if: always()
    needs:
      - markdownlint
      - yamllint
      - jsonlint
      - cookstylelint
      - integration-ubuntu-20_04
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures: 
          allowed-skips: 
          jobs: ${{ toJSON(needs) }}
